### ISSUE TITLE
iOS implementation

### ISSUE THREAD

**Issue by vahidvdn** [NickIliev/nativescript-receiving-shared-content#1]
Is there any plan for iOS implementation?

**Comment by NickIliev** [comment]
@vahidvdn on iOS the taks is not so trivial. The iOS can enable your application to be listed as an application to share to, via the Share Extension ([here](https://medium.com/@abhishekthaplithapliyal/ios-share-extension-930ba1ad3c3d)). However at this very moment the Application Extensions  are not supported officially in NativeScripr (feature request [here](https://github.com/NativeScript/nativescript-cli/issues/3965))


Possible solution can be achieved by manually tempering with the Xcode project and adding the share extension as described [here](https://www.nativescript.org/blog/making-a-today-widget-in-ios-with-nativescript-and-ui-for-nativescript)

**Comment by NickIliev** [comment]
@vahidvdn updated the readme with IOS instructions

**Comment by vahidvdn** [comment]
@NickIliev Thanks.
